### ISSUE TITLE
Add a "DISCARD ALL" instruction between each file run

### ISSUE THREAD

**Issue by brunobord** [peopledoc/django-north#33] opened 2018-06-07 09:10 UTC
* Django North version: latest
* Django version: Django 1.11
* Python version: 2.7
* Operating System: Debian (inside a LXC)
* starting of Postgres 9.6.8

### Description

When you're running several files that have a ``set search_path`` **and** that the SQL instructions do not contain explicit schema names (e.g. "INSERT INTO tablename" instead of "INSERT INTO schemaname.tablename"), it may happen the following:

0. opening ``file1.sql``
1. ``set search_path = X``;
2. a set of SQL instructions, that will be applied to schema X.
3. opening ``file2.sql`` -- this file doesn't explicitly change the search path, but assumes that the search path is the user's (e.g. "public")
4. a set of SQL instructions that will fail... because the current search_path **is still X**

Note: this behaviour was introduced by PG 9.6.8 for security reasons.

### Solution

We may want to explicitly run a SQL instruction that resets any contextual value (search_path included, but not only) after each file executed:

```sql
DISCARD ALL;
```

**Comment by brunobord** [comment] 2018-06-07 09:10
ping @marco44 for more detailed information on this matter.

**Comment by PierreDucroquet** [comment] 2018-06-07 09:27
No it's not. Settings are supposed to be reset at the end of each file.

**Comment by marco44** [comment] 2018-06-07 09:27
Well, that would mean that the execution of each script is dependant of the fact that the previous one hasn't forgot to reset its parameter. Wouldn't it be more robust to make sure that each script is run with a clean slate, directly from django north ?

**Comment by k4nar** [comment] 2018-06-07 09:34
But why is it different in the context of Django North than when you launch the migrations in production?

**Comment by marco44** [comment] 2018-06-07 09:34
We run those with psql. No django_north on our production servers.

**Comment by PierreDucroquet** [comment] 2018-06-07 09:35
That's why we must have the DISCARD ALL. Django north is the one being differente here.

**Comment by k4nar** [comment] 2018-06-07 09:36
So maybe the issue is the way Django North uses to run those scripts? I really don't get why it would be different than running them via psql.

**Comment by PierreDucroquet** [comment] 2018-06-07 09:37
Then django north can have fun closing and reopening sql sessions between each file. That's exactly the same as running discard all. Your choice.

**Comment by marco44** [comment] 2018-06-07 09:38
Because you are running all scripts in a single session. And since PG 9.6.8, pg_dump forces a set search_path to 'pg_catalog' at the start of the dump (for security reason, I can give you the CVE if you are interested). If you keep it that way, as would happen without a discard all, nothing else runs, as no object is other scripts is found.

**Comment by k4nar** [comment] 2018-06-07 09:40
Ok, I get it now. So `DISCARD ALL` it is then I guess. But it bothers me to run "extra SQL" not included in the migration files.

**Comment by marco44** [comment] 2018-06-07 09:54
Discard all is a fast way to do an equivalent of disconnect/reconnect. It's exactly what pgbouncer does when dispatching a session to a new client.

**Comment by zebuline** [comment] 2018-09-13 07:18
Done

**Closed by zebuline** 2018-09-13 07:18 UTC

**Comment by ewjoachim** [comment] 2020-07-22 07:35
Note: north now uses septentrion, and septentrion now runs every migration in a dedicated psql. This setting is no more !
